### ISSUE TITLE
Change required for AppCenter: Name

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/sudokular#2]
Thanks for submitting this fork @bartzaalberg! However, in order to respect the original author and project (along with allowing for them to resume their project and resubmit to AppCenter under their original name) we must ask that you rename and rebrand the app. I see you've changed the icon which is a good start, but you'll have to name it something other than "Sudoku" in all user-facing strings. The RDNN is fine as-is. Thanks!

**Comment by unbelievableflavour** [comment]
As i changed the RDNN. Isn't it possible for the original author to resume development? 

Also aren't there more apps with the same names in app stores? The name of the game is called Sudoku so that is the most obvious name for the application. So is it allowed to just call it Sudoku? Or do you have another proposal?

**Comment by cassidyjames** [comment]
@bartzaalberg we don't allow duplicate names in AppCenter to reduce user confusion. :smile: Each name should be unique. Even though it's not released for Juno, @parnold-x claimed that app name first and should continue to be able to use it if he does bring his app to Juno. It's not a technical limitation, but a branding/user confusion one.

I'm not sure what a good replacement name would be, but something more unique than "Sudoku" so users can easily distinguish it from the other app is required.
